[build]
builder = "nixpacks"
buildCommand = "npm ci && npx prisma generate && nest build"

[deploy]
startCommand = "npm run prisma:deploy:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PORT = "3000"
