[build]
builder = "nixpacks"
buildCommand = "npm ci && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma migrate deploy && npm run prisma:seed && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
