[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "npm run prisma:deploy:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
